#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin deps/jiffy/ebin deps/ej/ebin
-include("../include/chef_types.hrl").

main([Type | NodeFiles]) ->
    application:start(jiffy),
    [ do_deep_merge(Type, File) || File <- NodeFiles ],
    ok.

do_deep_merge(Type, File) ->
    {ok, Bin} = file:read_file(File),
    RawObject = jiffy:decode(Bin),
    Merged = ejson_for_type(Type, RawObject),
    OutFile = File ++ ".merged",
    file:write_file(OutFile, jiffy:encode(Merged)),
    ok.

ejson_for_type("nodes", RawObject) ->
    Name = ej:get({"name"}, RawObject),
    Env = ej:get({"chef_environment"}, RawObject),

    chef_node:ejson_for_indexing(#chef_node{name = Name,
                                                         environment = Env},
                                              RawObject).
